// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: answer.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const autoGradeMultipleChoice = `-- name: AutoGradeMultipleChoice :exec
UPDATE answers a
SET is_correct = o.is_correct,
    score = CASE WHEN o.is_correct THEN q.points ELSE 0 END
FROM options o
JOIN questions q ON q.id = a.question_id
WHERE a.selected_option_id = o.id
  AND q.type = 'multiple_choice'
  AND a.id = $1
`

func (q *Queries) AutoGradeMultipleChoice(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, autoGradeMultipleChoice, id)
	return err
}

const hasUngradedEssay = `-- name: HasUngradedEssay :one
SELECT EXISTS (
  SELECT 1
  FROM answers a
  JOIN questions q ON q.id = a.question_id
  WHERE a.attempt_id = $1
    AND q.type = 'essay'
    AND a.score IS NULL
)
`

func (q *Queries) HasUngradedEssay(ctx context.Context, attemptID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasUngradedEssay, attemptID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const upsertAnswer = `-- name: UpsertAnswer :one
INSERT INTO answers (
  attempt_id,
  question_id,
  selected_option_id,
  essay_answer,
  updated_at
) VALUES (
  $1, $2, $3, $4, now()
)
ON CONFLICT (attempt_id, question_id)
DO UPDATE SET
  selected_option_id = EXCLUDED.selected_option_id,
  essay_answer = EXCLUDED.essay_answer,
  updated_at = now()
RETURNING id, attempt_id, question_id, selected_option_id, essay_answer, is_correct, score, updated_at
`

type UpsertAnswerParams struct {
	AttemptID        pgtype.UUID `json:"attempt_id"`
	QuestionID       pgtype.UUID `json:"question_id"`
	SelectedOptionID pgtype.UUID `json:"selected_option_id"`
	EssayAnswer      pgtype.Text `json:"essay_answer"`
}

func (q *Queries) UpsertAnswer(ctx context.Context, arg UpsertAnswerParams) (Answer, error) {
	row := q.db.QueryRow(ctx, upsertAnswer,
		arg.AttemptID,
		arg.QuestionID,
		arg.SelectedOptionID,
		arg.EssayAnswer,
	)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.QuestionID,
		&i.SelectedOptionID,
		&i.EssayAnswer,
		&i.IsCorrect,
		&i.Score,
		&i.UpdatedAt,
	)
	return i, err
}
