// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Answer struct {
	ID               pgtype.UUID      `json:"id"`
	AttemptID        pgtype.UUID      `json:"attempt_id"`
	QuestionID       pgtype.UUID      `json:"question_id"`
	SelectedOptionID pgtype.UUID      `json:"selected_option_id"`
	EssayAnswer      pgtype.Text      `json:"essay_answer"`
	IsCorrect        pgtype.Bool      `json:"is_correct"`
	Score            pgtype.Int4      `json:"score"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

type ManualGrade struct {
	AnswerID pgtype.UUID      `json:"answer_id"`
	GraderID pgtype.UUID      `json:"grader_id"`
	Score    int32            `json:"score"`
	Feedback pgtype.Text      `json:"feedback"`
	GradedAt pgtype.Timestamp `json:"graded_at"`
}

type Option struct {
	ID         pgtype.UUID `json:"id"`
	QuestionID pgtype.UUID `json:"question_id"`
	OptionText string      `json:"option_text"`
	IsCorrect  pgtype.Bool `json:"is_correct"`
}

type Question struct {
	ID           pgtype.UUID `json:"id"`
	QuizID       pgtype.UUID `json:"quiz_id"`
	Type         string      `json:"type"`
	QuestionText string      `json:"question_text"`
	Points       int32       `json:"points"`
	OrderIndex   int32       `json:"order_index"`
}

type Quiz struct {
	ID              pgtype.UUID      `json:"id"`
	Title           string           `json:"title"`
	DurationSeconds int32            `json:"duration_seconds"`
	MaxAttempts     int32            `json:"max_attempts"`
	AutoGrading     pgtype.Bool      `json:"auto_grading"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

type QuizAttempt struct {
	ID            pgtype.UUID      `json:"id"`
	QuizID        pgtype.UUID      `json:"quiz_id"`
	UserID        pgtype.UUID      `json:"user_id"`
	AttemptNumber int32            `json:"attempt_number"`
	StartedAt     pgtype.Timestamp `json:"started_at"`
	FinishedAt    pgtype.Timestamp `json:"finished_at"`
	Status        string           `json:"status"`
}
