// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: option.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listOptionsByQuestionID = `-- name: ListOptionsByQuestionID :many
SELECT
  id,
  question_id,
  option_text
FROM options
WHERE question_id = $1
ORDER BY id
`

type ListOptionsByQuestionIDRow struct {
	ID         pgtype.UUID `json:"id"`
	QuestionID pgtype.UUID `json:"question_id"`
	OptionText string      `json:"option_text"`
}

func (q *Queries) ListOptionsByQuestionID(ctx context.Context, questionID pgtype.UUID) ([]ListOptionsByQuestionIDRow, error) {
	rows, err := q.db.Query(ctx, listOptionsByQuestionID, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOptionsByQuestionIDRow
	for rows.Next() {
		var i ListOptionsByQuestionIDRow
		if err := rows.Scan(&i.ID, &i.QuestionID, &i.OptionText); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
