// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: question.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listQuestionsByQuizID = `-- name: ListQuestionsByQuizID :many
SELECT
  id,
  quiz_id,
  type,
  question_text,
  points,
  order_index
FROM questions
WHERE quiz_id = $1
ORDER BY order_index ASC
`

func (q *Queries) ListQuestionsByQuizID(ctx context.Context, quizID pgtype.UUID) ([]Question, error) {
	rows, err := q.db.Query(ctx, listQuestionsByQuizID, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.QuizID,
			&i.Type,
			&i.QuestionText,
			&i.Points,
			&i.OrderIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
