// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quiz.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getQuizByID = `-- name: GetQuizByID :one
SELECT id, title, duration_seconds, max_attempts, auto_grading, created_at
FROM quizzes
WHERE id = $1
`

func (q *Queries) GetQuizByID(ctx context.Context, id pgtype.UUID) (Quiz, error) {
	row := q.db.QueryRow(ctx, getQuizByID, id)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.DurationSeconds,
		&i.MaxAttempts,
		&i.AutoGrading,
		&i.CreatedAt,
	)
	return i, err
}
